rule Trojan_DDoS_Win32_StormDDoS_service_2_20170424091947_1041_336 
{
	meta:
		judge = "black"
		threatname = "Trojan[DDoS]/Win32.StormDDoS.service"
		threattype = "DDOS"
		family = "StormDDoS"
		hacker = "None"
		refer = "f75da4ffcdca3f67b4b0f3f157b0f98b,9ce80c5323c8b13f1fe8bc3cf4041639"
		description = "None"
		comment = "None"
		author = "sxy"
		date = "2017-04-13"
	strings:
		$s0 = "Host: %s:%d"
		$s1 = "%s %s %s%d"
		$s3 = "%c%c%c%c%c%c.exe"
		$s4 = "Connection: Keep-Alive"
		$s5 = "%s%s%s%s%s%s%s%s%s%s%s"
		$s6 = "%d.%d.%d.%d"
		$s7 = "GET %s HTTP/1.1"
		$s8 = "URLDownloadToFileA"
		$s9 = "lpk"
		$s10 = "DNSFlood"
		$s11 = "360rp.exe"
		$s12 = "360sd.exe"
		$a0 = "Abcdef Hijklmno Qrs"
		$a1 = "Bcdefg Ijklmnop Rst"
		$a2 = "Cdefgh Jklmnopq Stu"
		$a3 = "Defghi Klmnopqr Tuv"
		$a4 = "Efghij Lmnopqrs Uvw"
		$a5 = "Fghijk Mnopqrst Vwx"
		$a6 = "Ghijkl Nopqrstu Wxy"
		$a7 = "Hijklm Opqrstuv Xya"
		$a8 = "Ijklmn Pqrstuvw Yab"
		$a9 = "Jklmno Qrstuvwx Abc"
		$a10 = "Klmnop Rstuvwxy Bcd"
		$a11 = "Lmnopq Stuvwxya Cde"
		$a12 = "Mnopqr Tuvwxyab Def"
		$a13 = "Nopqrs Uvwxyabc Efg"
		$a14 = "Opqrst Vwxyabcd Fgh"
		$a15 = "Pqrstu Wxyabcde Ghi"
		$a16 = "Qrstuv Xyabcdef Hij"
		$a17 = "Rstuvw Yabcdefg Ijk"
		$a18 = "Stuvwx Abcdefgh Jkl"
		$a19 = "Tuvwxy Bcdefghi Klm"
		$a20 = "Uvwxya Cdefghij Lmn"
		$a21 = "Vwxyab Defghijk Mno"
		$a22 = "Wxyabc Efghijkl Nop"
		$a23 = "Xyabcd Fghijklm Opq"
		$a24 = "Yabcde Ghijklmn Pqr"

	condition:
		(3 of ($s*) and 1 of ($a*))
}
